kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: {{ .Chart.Name }}
spec:
  serviceName: {{ .Chart.Name }}
  replicas: 1
  selector:
    matchLabels:
      name: {{ $.Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
        name: {{ .Chart.Name }}
    spec:
      imagePullSecrets:
        {{ range $secret := $.Values.global.imagePullSecrets }}
        - name: {{ $secret }}
        {{ end }}
      containers:
        - name: postgres
          image: {{ include "image" . }}
          env:
            - name: POSTGRESQL_PASSWORD
              value: {{ $.Values.postgresPassword }}
          ports:
            - name: postgres
              containerPort: 5403
          volumeMounts:
            - name: storage
              mountPath: /bitnami/postgresql
            - name: init-database
              mountPath: /docker-entrypoint-initdb.d/
      volumes:
        - name: init-database
          configMap:
            name: init-database
      initContainers:
        - name: volume-permissions
          image: {{ .Values.busyboxImage }}
          imagePullPolicy: IfNotPresent
          command: ["sh", "-c", "chmod -R 777 /bitnami/postgresql/data"]
          securityContext:
            runAsUser: 0
          volumeMounts:
            - name: storage
              mountPath: "/bitnami/postgresql/data"
              readOnly: false
  volumeClaimTemplates:
    - metadata:
        name: storage
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: {{ $.Values.storage }}
